--- #YAML:1.0
name:               Acme-POE-Tree
version:            1.01
abstract:           Merry Christmas from the POE Team
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Curses:   1.15
    IO::Tty:  1.07
    POE:      1.003
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
